chore: read all messages from a file
nopeless/eliza pull request #3
Opened 2023-06-19 04:32 UTC by me505

2023-06-19 04:43 UTC, nopeless requested changes

2023-06-19 04:43 UTC, nopeless commented on test/should-not-reply.spec.ts
> +console.log(client);
remove

2023-06-19 04:43 UTC, nopeless commented on test/should-not-reply.spec.ts
> +			expect(m.mockReplies).to.have.length(0);
should be
`expect(..., Client shouldl not reply to '${message}'`

2023-06-19 04:43 UTC, nopeless commented on test/should-not-reply.spec.ts
> +		test(message, async () => {
```js
test('file', async () => {
  for (const message of messages) { ... }
  }
)
```

Current test scheme spams console too much

2024-02-14 10:45 UTC, BeanieMen commented
Hey nop, i forgor what the issue wanted me to do, i am gonna pick this up again. Can you explain what i had to do

2024-02-14 14:46 UTC, BeanieMen commented
HOW DID I WRITE SUCH SHIT CODE WTF

2024-02-15 12:04 UTC, BeanieMen commented
Please?

2024-02-15 18:31 UTC, nopeless commented
fix eslint errors

the goal is to check if the bot properly ignores normal messages

2024-02-17 12:51 UTC, closed without merging

2024-02-17 13:13 UTC, BeanieMen commented
> fix eslint errors
> 
> the goal is to check if the bot properly ignores normal messages

idk what i did in this pr
I am getting no eslint errors and using your tests i can confirm it is ignoring normal messages

2024-02-17 13:13 UTC, BeanieMen commented
It is failing one test called "tl shorthand" tho

2024-02-17 20:25 UTC, nopeless commented
@BeanieMen read PR title